#!/usr/bin/env python
import json
import subprocess
import os


def config_changed():
    userpass = subprocess.check_output(["config-get", "auth"])
    filename = "/var/lib/camlistore/.config/camlistore/server-config.json"

    if os.path.exists(filename):
        with open(filename) as f:
            data = json.loads(f.read())
            data["auth"] = userpass.strip()
        with open(filename, 'w') as f:
            f.write(json.dumps(data))
 
    subprocess.call(["service", "camlistore", "stop"])
    subprocess.check_call(["service", "camlistore", "start"])


if __name__ == '__main__':
    config_changed()
